In [476]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [477]:
data= pd.read_csv(r"C:\Users\ritvikpalvankar7\Desktop\FML\crab.txt",delimiter='\t')
data.to_csv('crab.csv')

In [478]:
data.head()


Species  FrontalLip  RearWidth  Length  Width  Depth  Male  Female
0        0        20.6       14.4    42.8   46.5   19.6     1       0
1        1        13.3       11.1    27.8   32.3   11.3     1       0
2        0        16.7       14.3    32.3   37.0   14.7     0       1
3        1         9.8        8.9    20.4   23.9    8.8     0       1
4        0        15.6       14.1    31.0   34.5   13.8     0       1

In [479]:
data.describe().transpose()

count     mean       std   min     25%    50%     75%   max
Species     200.0   0.5000  0.501255   0.0   0.000   0.50   1.000   1.0
FrontalLip  200.0  15.5830  3.495325   7.2  12.900  15.55  18.050  23.1
RearWidth   200.0  12.7385  2.573340   6.5  11.000  12.80  14.300  20.2
Length      200.0  32.1055  7.118983  14.7  27.275  32.10  37.225  47.6
Width       200.0  36.4145  7.871955  17.1  31.500  36.80  42.000  54.6
Depth       200.0  14.0305  3.424772   6.1  11.400  13.90  16.600  21.6
Male        200.0   0.5000  0.501255   0.0   0.000   0.50   1.000   1.0
Female      200.0   0.5000  0.501255   0.0   0.000   0.50   1.000   1.0

In [480]:
colnames_numeric = data_2C.columns[0:6]

In [481]:
data.head()

Species  FrontalLip  RearWidth  Length  Width  Depth  Male  Female
0        0        20.6       14.4    42.8   46.5   19.6     1       0
1        1        13.3       11.1    27.8   32.3   11.3     1       0
2        0        16.7       14.3    32.3   37.0   14.7     0       1
3        1         9.8        8.9    20.4   23.9    8.8     0       1
4        0        15.6       14.1    31.0   34.5   13.8     0       1

In [482]:
#Splitting the data into 140 and 60 samples respectively
train_index=int(0.7*len(data))
data_train,data_test=data[:train_index:],data[train_index:]
t_train=data_train.Species
t_test=data_test.Species

In [483]:
t_train.shape

(140,)

In [484]:
t_test.shape

(60,)

In [485]:
del data_train['Species']
del data_test['Species']
del data_test['Female']
del data_train['Female']

In [486]:
data_test.shape

(60, 6)

In [487]:
data_train.shape

(140, 6)

In [488]:
pC1 = np.sum(t_train==1)/t_train.size
pC0 = np.sum(t_train==0)/t_train.size
pC0, pC1

(0.5142857142857142, 0.4857142857142857)

In [489]:
data['Species'].value_counts()

1    100
0    100
Name: Species, dtype: int64

In [490]:
X=np.array(data_train)
X.shape


(140, 6)

In [491]:
mu0 = np.mean(X[t_train==0,:],axis=0) #Calculating mean for class0
mu1 = np.mean(X[t_train==1,:],axis=0) #Calculating mean for class1
print(mu0)
print(mu1)

[17.10555556 13.62083333 34.1375     38.10277778 15.46527778  0.51388889]
[14.03529412 11.84705882 30.08676471 34.73382353 12.56764706  0.51470588]


In [492]:
cov0 = np.cov(X[t_train==0,:].T) #Calculating covariance for class0
cov1 = np.cov(X[t_train==1,:].T) #Calculating covariance for class1
print(cov0)
print(cov1)

[[ 9.29827856  7.23185446 18.83640845 21.15223787  8.68850548 -0.43106416]
 [ 7.23185446  6.85913732 14.3518838  16.57768779  6.55777582 -0.79254695]
 [18.83640845 14.3518838  38.99167254 43.51876761 18.02005282 -0.63644366]
 [21.15223787 16.57768779 43.51876761 48.98168232 20.07671753 -0.92539124]
 [ 8.68850548  6.55777582 18.02005282 20.07671753  8.43948161 -0.26218701]
 [-0.43106416 -0.79254695 -0.63644366 -0.92539124 -0.26218701  0.25332551]]
[[ 9.21903424  5.97159789 21.19107112 24.21281826  9.46712906  0.56365233]
 [ 5.97159789  4.57118525 13.72510975 15.78868306  6.24841089  0.06944688]
 [21.19107112 13.72510975 49.21638938 56.12493196 21.88956541  1.40094381]
 [24.21281826 15.78868306 56.12493196 64.1691374  25.01991659  1.52561457]
 [ 9.46712906  6.24841089 21.88956541 25.01991659  9.89117647  0.55122915]
 [ 0.56365233  0.06944688  1.40094381  1.52561457  0.55122915  0.25351185]]


In [493]:
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

In [494]:
y1 = multivariate_normal.pdf(X, mean=mu1, cov=cov1,)
y0 = multivariate_normal.pdf(X, mean=mu0, cov=cov0,)

In [495]:
pos0 = (y0*pC0)/(y1*pC1 + y0*pC0)
pos1 = (y1*pC1)/(y1*pC1 + y0*pC0)

# Calculation of probabilties

In [496]:
y0new = multivariate_normal.pdf(data_test, mean=mu0, cov=cov0) #P(x|C0)
y1new = multivariate_normal.pdf(data_test, mean=mu1, cov=cov1) #P(x|C1)

In [497]:
y0new, y1new

(array([5.52908646e-03, 1.19567639e-02, 7.55839312e-14, 3.14603377e-13,
        1.18435549e-09, 8.04200156e-05, 6.11910190e-09, 1.60327224e-04,
        6.34032230e-03, 1.36326532e-02, 2.17024147e-03, 5.35161630e-11,
        2.28570347e-04, 8.03305011e-11, 1.51564563e-04, 2.97397912e-04,
        7.24011537e-09, 1.08433497e-02, 8.30968939e-04, 1.22027557e-10,
        1.06708280e-12, 5.04631854e-05, 9.40221137e-05, 4.40489200e-07,
        7.75106489e-07, 2.43661916e-09, 2.97900474e-04, 4.74383061e-05,
        9.33591599e-07, 1.27856683e-07, 4.28482756e-03, 3.89366331e-09,
        3.68444754e-10, 8.14768974e-06, 2.38560013e-08, 5.80681716e-04,
        1.60562908e-06, 6.64579218e-03, 7.18451019e-03, 3.48782583e-11,
        5.77443568e-09, 1.71501663e-06, 3.19907619e-09, 5.71188423e-09,
        2.05711195e-09, 2.07675696e-04, 4.75589781e-06, 4.61205650e-10,
        4.44504585e-03, 1.22814772e-08, 1.03580878e-02, 3.00521041e-04,
        5.93096851e-04, 1.99332843e-03, 1.21554081e-04, 1.218240

In [498]:
pos0new = (y0new*pC0)/(y1new*pC1 + y0new*pC0)
pos1new = (y1new*pC1)/(y1new*pC1 + y0new*pC0)

In [499]:
pos0new, pos1new 

(array([1.00000000e+00, 1.00000000e+00, 2.95597932e-09, 3.99596725e-10,
        4.51797541e-08, 9.85684814e-01, 8.08228897e-05, 1.00000000e+00,
        1.00000000e+00, 9.99999999e-01, 1.00000000e+00, 2.39142456e-06,
        1.00000000e+00, 1.30379708e-06, 1.00000000e+00, 1.00000000e+00,
        1.33057287e-04, 9.99999751e-01, 9.95078362e-01, 4.20506740e-08,
        3.73608773e-10, 1.00000000e+00, 9.99977842e-01, 4.29291907e-04,
        3.01611179e-05, 2.06168937e-06, 9.99982066e-01, 1.00000000e+00,
        1.15140009e-04, 9.47583829e-06, 9.99999888e-01, 3.21720028e-07,
        1.96275844e-04, 3.34069156e-03, 2.01565074e-05, 1.00000000e+00,
        3.87450793e-04, 1.00000000e+00, 1.00000000e+00, 8.11763907e-07,
        6.00015272e-07, 4.83095225e-04, 8.45147526e-07, 2.53635924e-06,
        6.12234988e-07, 9.99999999e-01, 6.48461025e-04, 3.14919971e-06,
        9.99989945e-01, 4.51491506e-06, 9.99999903e-01, 9.99999984e-01,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 3.558124

In [500]:
class0=y0new*pC0
class0_train=y0*pC0

In [501]:
class1=y1new*pC1
class1_train=y1*pC1
myclass=np.zeros(60)
classtrain=np.zeros(140)

In [502]:
for i in range(60):   #for testing
    if class0[i]>class1[i]:
        myclass[i]=0
    elif (class1[i]>class0[i]): 
        myclass[i]=1

        #for training
for i in range(140):   
    if class0_train[i]>class1_train[i]:
        my_classtrain[i]=0
    elif (class1_train[i]>class0_train[i]): 
        my_classtrain[i]=1

In [503]:
my_classtrain

array([0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0.])

In [504]:
#for confusion matrix
pd.crosstab(t_test,myclass,colnames=['Predicted Species'])

Predicted Species  0.0  1.0
Species                    
0                   28    0
1                    0   32

In [505]:
#for training confusion matrix
pd.crosstab(t_train,my_classtrain,colnames=['Predicted Species'])

Predicted Species  0.0  1.0
Species                    
0                   72    0
1                    0   68

# K-NN Implementation

In [506]:
df = data.values.tolist()

In [507]:
train_index=int(0.7*len(df))
train,test=df[:train_index:],df[train_index:]


In [508]:
len(train)

140

In [466]:
len(test)

60

In [467]:
import math
def Euclideandist(x,xi, length):
    distance = 0.0
    for i in range(length):
        distance += pow(float(x[i])- float(xi[i]),2)
    return math.sqrt(distance)

In [468]:
import operator
def getN(train, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = Euclideandist(testInstance, train[x], length)
        distances.append((train[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

In [469]:
import operator
def getResponse(neighbors):
	classVotes = {}
	for x in range(len(neighbors)):
		response = neighbors[x][-1]
		if response in classVotes:
			classVotes[response] += 1
		else:
			classVotes[response] = 1
	sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)#Sorting it based on votes
	return sortedVotes[0][0] #Please note we need the class for the top voted class, hence [0][0]#

In [470]:
def getAccuracy(test, predictions):
	correct = 0
	for x in range(len(test)):
		if test[x][-1] == predictions[x]:
			correct += 1
	return (correct/float(len(test))) * 100.0


# Testing the functions for different values of k(1,2,3,4)

In [471]:
#K=1
k=1
predictions=[]

for x in range(len(test)):
    neighbors = getN(train, test[x], k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(test[x][-1]))
accuracy = getAccuracy(test, predictions)
print('Accuracy: ' + repr(accuracy) + '%')    

> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, act

In [472]:
#K=2
k=2
predictions=[]

for x in range(len(test)):
    neighbors = getN(train, test[x], k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(test[x][-1]))
accuracy = getAccuracy(test, predictions)
print('Accuracy: ' + repr(accuracy) + '%')    

> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, act

In [473]:
#K=3
k=3
predictions=[]

for x in range(len(test)):
    neighbors = getN(train, test[x], k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(test[x][-1]))
accuracy = getAccuracy(test, predictions)
print('Accuracy: ' + repr(accuracy) + '%')    

> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, act

In [474]:
#K=4
k=4
predictions=[]

for x in range(len(test)):
    neighbors = getN(train, test[x], k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(test[x][-1]))
accuracy = getAccuracy(test, predictions)
print('Accuracy: ' + repr(accuracy) + '%')


> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, act

# Question2.5 When k goes on increasing, the model will be simple. All the test points will belong to the same class:the majority class. This is under fit, that is, high bias and low variance. When k decreases,the resolution is too fin, which is overfit,which indicates high variance. The accuracy decreases as k increases


# Question2.2 I faced dimensions problems while plotting the probability distribution which I overcame by checking the array 

# Question2.7 The generative model is better as compared to the discriminative as it has better accuracy